make possible to update service of type clusterIP
if clusterIP is set helm can not update version
reports error:
Error: UPGRADE FAILED: cannot patch "mockserver" with kind Service: Service "mockserver" is invalid: spec.clusterIP: Invalid value: "": field is immutable